# This is a basic workflow to help you get started with Actions

name: Publish to Automation-Hub

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: arc-runner-enterprise

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Ansible Publish
        uses: ansible/ansible-publish-action@v1.0.0
        with:
          # Galaxy API key to use
          api_key: '${{ secrets.AAP_HUB_TOKEN }}'
          api_server: https://platform.aapjecq2y5bgr4mu.ansiblecloud.redhat.com/api/galaxy/
